---
name: FLV-Info
version: 0.03
author:
  - 'Clotho Advanced Media, Inc. <cpan@clotho.com>'
abstract: Extract metadata from Flash Video files
license: perl
resources:
  license: perl://dev.perl.org/licenses/
requires:
  AMF::Perl: 0.15
  Digest::MD5: 0
  List::Util: 0
  SWF::File: 0
build_requires:
  Test::More: 0
provides:
  FLV::AMFReader:
    file: lib/FLV/AMFReader.pm
    version: 0.03
  FLV::AMFWriter:
    file: lib/FLV/AMFWriter.pm
    version: 0.03
  FLV::AudioTag:
    file: lib/FLV/AudioTag.pm
    version: 0.03
  FLV::Base:
    file: lib/FLV/Base.pm
    version: 0.03
  FLV::Body:
    file: lib/FLV/Body.pm
    version: 0.03
  FLV::Constants:
    file: lib/FLV/Constants.pm
    version: 0.03
  FLV::File:
    file: lib/FLV/File.pm
    version: 0.03
  FLV::FromSWF:
    file: lib/FLV/FromSWF.pm
    version: 0.03
  FLV::Header:
    file: lib/FLV/Header.pm
    version: 0.03
  FLV::Info:
    file: lib/FLV/Info.pm
    version: 0.03
  FLV::MetaTag:
    file: lib/FLV/MetaTag.pm
    version: 0.03
  FLV::Tag:
    file: lib/FLV/Tag.pm
    version: 0.03
  FLV::VideoTag:
    file: lib/FLV/VideoTag.pm
    version: 0.03
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
